services:
  - type: web
    name:  bookmark-backend    
    runtime: node
    repoWorkspace: backend     
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FRONTEND_URL
        fromService:
          type: web
          name: bookmark-frontend
          property: host

  - type: web
    name: bookmark-frontend
    runtime: static             
    repoWorkspace: frontend      
    publishPath: .               
